"""
I/O utilities for file, database, HTTP, JSON-RPC, and object storage operations
"""

from axiompy.io.database import (
    Database,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseFactory,
    DatabaseQueryError,
    DatabaseSettings,
    DatabaseType,
    DynamoDBDatabase,
    MySQLDatabase,
    PostgreSQLDatabase,
    SQLiteDatabase,
)
from axiompy.io.file import (
    CachedReader,
    read_binary,
    read_csv,
    read_json,
    read_lines,
    read_multiple,
    read_text,
    read_with_path_expansion,
    read_yaml,
    safe_read,
    set_default_logger,
)
from axiompy.io.http import (
    AuthType,
    HTTPAuthError,
    HTTPClient,
    HTTPClientError,
    HTTPClientFactory,
    HTTPClientSettings,
    HTTPConnectionError,
    HTTPRequestError,
    HTTPTransport,
    RetryConfig,
)
from axiompy.io.http_async import (
    AsyncHTTPClient,
    AsyncHTTPClientFactory,
    AsyncHTTPClientProtocol,
    HTTPBatchResponses,
    HTTPBatchSlotBuilder,
    HTTPCallBatch,
    HTTPExchangeResult,
    HTTPExchangeStatus,
    HTTPMethod,
    MockAsyncHTTPClient,
    MockHTTPBatchSlotBuilder,
    MockHTTPCallBatch,
)
from axiompy.io.jsonrpc import (
    JSONRPCClient,
    JSONRPCClientError,
    JSONRPCClientFactory,
    JSONRPCClientSettings,
    JSONRPCConnectionError,
    JSONRPCErrorCode,
    JSONRPCMethodError,
    JSONRPCProtocolError,
    JSONRPCRequestBuilder,
    JSONRPCResponse,
    MockJSONRPCClient,
)
from axiompy.io.object import (
    AzureBlobStorage,
    GCSObjectStorage,
    ObjectMetadata,
    ObjectNotFoundError,
    ObjectOperationError,
    ObjectStorage,
    ObjectStorageError,
    ObjectStorageFactory,
    S3ObjectStorage,
    StorageConnectionError,
    StorageSettings,
    StorageType,
)
from axiompy.io.serialization import (
    Deserializer,
    DeserializerFactory,
    JSONDeserializer,
    JSONSerializer,
    SerializationError,
    SerializationFormat,
    Serializer,
    SerializerFactory,
    XMLDeserializer,
    YAMLDeserializer,
)

__all__ = [
    # File reading utilities
    "read_text",
    "read_json",
    "read_lines",
    "read_csv",
    "read_yaml",
    "read_binary",
    "safe_read",
    "read_multiple",
    "read_with_path_expansion",
    "CachedReader",
    # Configuration
    "set_default_logger",
    # Database
    "Database",
    "DatabaseFactory",
    "DatabaseType",
    "DatabaseSettings",
    "DatabaseError",
    "DatabaseConnectionError",
    "DatabaseQueryError",
    "MySQLDatabase",
    "PostgreSQLDatabase",
    "DynamoDBDatabase",
    "SQLiteDatabase",
    # Object Storage
    "ObjectStorage",
    "ObjectStorageFactory",
    "StorageType",
    "StorageSettings",
    "ObjectMetadata",
    "ObjectStorageError",
    "StorageConnectionError",
    "ObjectNotFoundError",
    "ObjectOperationError",
    "S3ObjectStorage",
    "GCSObjectStorage",
    "AzureBlobStorage",
    # HTTP Client
    "HTTPClient",
    "HTTPClientFactory",
    "HTTPClientSettings",
    "HTTPClientError",
    "HTTPConnectionError",
    "HTTPRequestError",
    "HTTPAuthError",
    "HTTPTransport",
    "RetryConfig",
    "AuthType",
    # Async HTTP batch
    "AsyncHTTPClient",
    "AsyncHTTPClientFactory",
    "AsyncHTTPClientProtocol",
    "HTTPBatchResponses",
    "HTTPBatchSlotBuilder",
    "HTTPCallBatch",
    "HTTPExchangeResult",
    "HTTPExchangeStatus",
    "HTTPMethod",
    "MockAsyncHTTPClient",
    "MockHTTPCallBatch",
    "MockHTTPBatchSlotBuilder",
    # JSON-RPC Client
    "JSONRPCClient",
    "JSONRPCClientFactory",
    "JSONRPCClientSettings",
    "JSONRPCClientError",
    "JSONRPCConnectionError",
    "JSONRPCProtocolError",
    "JSONRPCMethodError",
    "JSONRPCErrorCode",
    "JSONRPCRequestBuilder",
    "JSONRPCResponse",
    "MockJSONRPCClient",
    # Serialization
    "Serializer",
    "Deserializer",
    "SerializationFormat",
    "SerializationError",
    "JSONSerializer",
    "JSONDeserializer",
    "XMLDeserializer",
    "YAMLDeserializer",
    "SerializerFactory",
    "DeserializerFactory",
]
