"""
Domain layer - Core business entities.

This module contains domain entities that represent the core business concepts.
Domain entities own business logic and are independent of HTTP and database concerns.

In production, domain entities would typically live in the axiompy shared library
and be imported by multiple services.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class Resource:
    """
    Resource domain entity - the core business concept.

    This is a pure domain object with no HTTP or database concerns.
    Business logic and validation rules are defined at this level.

    Attributes:
        id: Unique identifier (auto-generated by database)
        name: Resource name (required, 1-255 chars)
        description: Human-readable description (optional)
        created_at: Timestamp when created (auto-generated)
        updated_at: Timestamp when last updated (auto-generated)
    """

    name: str
    description: Optional[str] = None
    id: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Resource":
        """
        Create a Resource from a dictionary (from repository).

        Args:
            data: Dictionary with resource fields

        Returns:
            Resource instance
        """
        return cls(
            id=data.get("id"),
            name=data.get("name"),
            description=data.get("description"),
            created_at=data.get("created_at"),
            updated_at=data.get("updated_at"),
        )

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert Resource to dictionary (for repository persistence).

        Returns:
            Dictionary representation of resource
        """
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }
